config/routes.rb
Webehr::Application.routes.draw do
  
  root :to => "profiles#index"
  
  resources :profiles, :except => [:show] do
    resources :medications, :except => [:show]
    resources :results, :except => [:show]
  end
  
  resources :users, :only => [:index]
  
  resource :account, :only => [:show, :edit, :update] do
    get :edit_password
    put :update_password
  end
  
  devise_for :users

  namespace :api do
    resources :profiles, :only => [:index] do
      resources :medications, :only => [:create, :destroy]
      resources :results, :only => [:create, :destroy]
    end
  end
  
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  GENDERS = {0 => "Male", 1 => "Female"}
  BLOOD_TYPES = ["A+", "B+", "AB+", "0+", "A-", "B-", "AB-", "0-"]
  
  # ================
  # = associations =
  # ================
  has_many :medications, :dependent => :destroy
  has_many :results, :dependent => :destroy
  has_many :assignments, :dependent => :destroy
  has_many :users, :through => :assignments
  
  # ===============
  # = validations =
  # ===============
  validates :name, :birth_date, :blood_type, :gender, :presence => true
  
  def gender_name
    GENDERS[self.gender]
  end
  
end

app/controllers/api/profiles_controller.rb
class Api::ProfilesController < Api::BaseController
  
  def index
    @profiles = current_user.profiles.includes([:medications, :results]).all
    
    # Configure json output
    profile_fields = [:id, :name, :birth_date, :blood_type, :gender]
    medication_fields = [:id, :name, :started_date, :ended_date, :strength, :route, :dose, :frequency, :note, :profile_id]
    result_fields = [:id, :name, :result, :units, :date, :note, :profile_id]
    
    json_config = {:only => profile_fields, 
                   :include => {
                     :medications => {:only => medication_fields}, 
                     :results => {:only => result_fields} 
                     }
                  } 
    
    render :json => @profiles.to_json(json_config)
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :find_resource, :only => [:edit, :update, :destroy]
  before_filter :assign_current_user, :only => [:create, :update]
  
  def index
    @search = current_user.profiles.search(params[:search])
    @search.meta_sort ||= "name.desc"
    @profiles = @search.paginate :per_page => 20, :page => params[:page]
    
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def new
    @profile = current_user.profiles.build
  end

  def create
    @profile = current_user.profiles.build(params[:profile])
    if @profile.save
      flash[:notice] = "Profile was successfully created"
      redirect_to profile_medications_path(@profile)
    else
      render :action => "new"
    end
  end
  
  def edit
  end
  
  def update
    if @profile.update_attributes(params[:profile])
      flash[:notice] = "Profile was successfully updated"
      redirect_to profile_medications_path(@profile)
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @profile.destroy
    
    flash[:notice] = "Profile was successfully deleted"
    redirect_to profiles_path
  end
  
  private
  def find_resource
    @profile = current_user.profiles.find(params[:id])
  end
  
  def assign_current_user
    params[:profile][:user_ids] ||= []
    params[:profile][:user_ids] << current_user.id
  end
end

app/helpers/api/profiles_helper.rb
module Api::ProfilesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.haml
= simple_form_for @profile do |f|
  = f.input :name
  = f.input :gender, :as => :radio, :collection => Profile::GENDERS.invert
  = f.input :blood_type, :as => :select, :collection => Profile::BLOOD_TYPES
  = f.input :birth_date
  = f.association :users, :collection => User.all
  = f.button :submit, "Save"

app/views/profiles/_header.html.haml
#profile_header
  .top
    %h2= @profile.name
    %ul.crud_menu
      %li.edit= link_to "Edit", edit_profile_path(@profile)
      %li.delete= link_to "Delete", profile_path(@profile), :method => :delete, :confirm => "Do you really want to delete this profile?"
  .labeled_info
    %p
      %span.label Gender
      %span= @profile.gender_name
    %p
      %span.label Birth date
      %span= l(@profile.birth_date)
    %p
      %span.label Blood type
      %span= @profile.blood_type
  
  %ul.crud_menu
    %li.medications= link_to "Medications", profile_medications_path(@profile)
    %li.results= link_to "Results", profile_results_path(@profile)
  

app/views/profiles/_profiles.html.haml
%table.zebra
  %tr
    %th{:style => "width: 35%"}= sort_link @search, :name, "Name"
    %th{:style => "width: 15%"}= sort_link @search, :gender, "Gender"
    %th{:style => "width: 15%"}= sort_link @search, :blood_type, "Blood type"
    %th{:style => "width: 15%"}= sort_link @search, :birth_date, "Birth date"
    %th{:style => "width: 20%"}= sort_link @search, :created_at, "Created at"
  - profiles.each do |profile|
    %tr.row{:class => cycle('even', 'odd')}
      %td= link_to profile.name, profile_medications_path(profile)
      %td= profile.gender_name
      %td= profile.blood_type
      %td= l(profile.birth_date) if profile.birth_date.present?
      %td= l(profile.created_at)
= will_paginate profiles

app/views/profiles/edit.html.haml
%h2 Edit profile

= render "form"

app/views/profiles/index.html.haml
%h2 Profiles

.top
  .search
    = text_field_tag :query, nil
    = image_tag "ajax_loader.gif", :class => "indicator", :style => "display:none;"
  .add_link= link_to "New profile", new_profile_path

- if @profiles.present?
  #profiles_container
    = render "profiles", :profiles => @profiles
    .search_results
- else
  %p No profiles found.

app/views/profiles/index.js.erb
$('#profiles_container table').hide();
$('#profiles_container .search_results').html('<%= escape_javascript render("profiles", :profiles => @profiles) %>');
$('.search .indicator').hide();

app/views/profiles/new.html.haml
%h2 New profile

= render "form"