config/routes.rb
Webehr::Application.routes.draw do
  
  root :to => "profiles#index"
  
  resources :profiles, :except => [:show] do
    resources :medications, :except => [:show]
    resources :results, :except => [:show]
  end
  
  resources :users, :only => [:index]
  
  resource :account, :only => [:show, :edit, :update] do
    get :edit_password
    put :update_password
  end
  
  devise_for :users

  namespace :api do
    resources :profiles, :only => [:index] do
      resources :medications, :only => [:create, :destroy]
      resources :results, :only => [:create, :destroy]
    end
  end
  
end

app/models/medication.rb
class Medication < ActiveRecord::Base
  ROUTES = ["By mouth", "Injection", "Inhaled", "To eyes", "To skin", "To nose"]
  DOSES = ["1/4", "1/2", "1", "2", "3", "4", "5"]
  FREQUENCIES = ["1 time per day", "1 time per day in the morning", "1 time per day in the evening", "2 times per day", "3 times per day", "4 times per day", "every hour"]
  
  # ================
  # = associations =
  # ================
  belongs_to :profile
  
  # ===============
  # = validations =
  # ===============
  validates :name, :started_date, :ended_date, :route, :strength, :dose, :frequency, :presence => true
  
end

app/controllers/api/medications_controller.rb
class Api::MedicationsController < Api::BaseController
  before_filter :find_profile
  
  def create
    @medication = @profile.medications.build(params[:medication])

    if @medication.save
      render :json => @medication, :status => :created
    else
      render :json => {:errors => @medication.errors.full_messages}, :status => :unprocessable_entity
    end
  end
  
  def destroy
    @medication = @profile.medications.find(params[:id])
    @medication.destroy
    
    head :ok
  end
  
  private
  def find_profile
    @profile = current_user.profiles.find(params[:profile_id])
  end
end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController
  before_filter :find_parent_resource
  before_filter :find_resource, :only => [:edit, :update, :destroy]

  def index
    @search = @profile.medications.search(params[:search])
    @search.meta_sort ||= "created_at.desc"
    @medications = @search.paginate :per_page => 20, :page => params[:page]
  end

  def new
    @medication = @profile.medications.build
  end

  def create
    @medication = @profile.medications.build(params[:medication])
    
    if @medication.save
      flash[:notice] = "Medication was successfully created"
      redirect_to profile_medications_path(@profile)
    else
      render :action => "new"
    end
  end

  def edit
    @profile = @medication.profile
  end
  
  def update
    @profile = @medication.profile
    
    if @medication.update_attributes(params[:medication])
      flash[:notice] = "Medication was successfully updated"
      redirect_to profile_medications_path(@profile)
    else
      render :action => "edit"
    end
  end

  def destroy
    @medication.destroy
    
    flash[:notice] = "Medication was successfully deleted"
    redirect_to profile_medications_path(@medication.profile)
  end
  
  private
  def find_parent_resource
    @profile = current_user.profiles.find(params[:profile_id])
  end
  
  def find_resource
    @medication = @profile.medications.find(params[:id])
  end
end

app/helpers/api/medications_helper.rb
module Api::MedicationsHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/views/medications/_form.html.haml
= simple_form_for [@profile, @medication] do |f|
  = f.input :name
  = f.input :started_date
  = f.input :ended_date
  = f.input :route, :as => :select, :collection => Medication::ROUTES
  = f.input :strength
  = f.input :dose, :label => "How many?", :as => :select, :collection => Medication::DOSES
  = f.input :frequency, :label => "How often?", :as => :select, :collection => Medication::FREQUENCIES
  = f.input :note
  = f.button :submit, "Save"

app/views/medications/edit.html.haml
= render "profiles/header", :profile => @profile

%h2 Edit medication

= render "form"

app/views/medications/index.html.haml
= render "profiles/header", :profile => @profile

%h2 Medications

.add_link= link_to "New medication", new_profile_medication_path(@profile)

- if @medications.present?
  #medications_container
    %table.zebra
      %tr
        %th{:style => "width: 20%"}= sort_link @search, :name, "Name"
        %th{:style => "width: 17%"} Duration
        %th{:style => "width: 15%"}= sort_link @search, :route, "Route"
        %th{:style => "width: 20%"} Dose
        %th.right{:style => "width: 20%"}= sort_link @search, :created_at, "Created at"
        %th{:style => "width: 8%"}
      - @medications.each do |medication|
        %tr{:class => cycle('even', 'odd')}
          %td= medication.name
          %td
            = "#{(medication.ended_date - medication.started_date).to_i} days"
            %br/
            %small= "from #{l(medication.started_date)}"
          %td= medication.route
          %td
            = "#{medication.dose} (#{medication.strength})"
            %br/
            = medication.frequency
          %td.right= l(medication.created_at)
          %td
            %ul.icon_menu
              %li= link_to image_tag("icons/edit.png", :alt => "edit"), edit_profile_medication_path(@profile, medication)
              %li= link_to image_tag("icons/delete.png", :alt => "delete"), profile_medication_path(@profile, medication), :method => :delete, :confirm => "Do you really want to delete this medication?"
  = will_paginate @medications
- else
  %p No medications found.

app/views/medications/new.html.haml
= render "profiles/header", :profile => @profile

%h2 New medication

= render "form"