config/routes.rb
Webehr::Application.routes.draw do
  
  root :to => "profiles#index"
  
  resources :profiles, :except => [:show] do
    resources :medications, :except => [:show]
    resources :results, :except => [:show]
  end
  
  resources :users, :only => [:index]
  
  resource :account, :only => [:show, :edit, :update] do
    get :edit_password
    put :update_password
  end
  
  devise_for :users

  namespace :api do
    resources :profiles, :only => [:index] do
      resources :medications, :only => [:create, :destroy]
      resources :results, :only => [:create, :destroy]
    end
  end
  
end

app/models/result.rb
class Result < ActiveRecord::Base
  # ================
  # = associations =
  # ================
  belongs_to :profile
  
  # ===============
  # = validations =
  # ===============
  validates :name, :result, :units, :date, :presence => true
end

app/controllers/api/results_controller.rb
class Api::ResultsController < Api::BaseController
  before_filter :find_profile
  
  def create
    @result = @profile.results.build(params[:result])

    if @result.save
      render :json => @result, :status => :created
    else
      render :json => {:errors => @result.errors.full_messages}, :status => :unprocessable_entity
    end
  end
  
  def destroy
    @result = @profile.results.find(params[:id])
    @result.destroy
    
    head :ok
  end
  
  private
  def find_profile
    @profile = current_user.profiles.find(params[:profile_id])
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_filter :find_parent_resource
  before_filter :find_resource, :only => [:edit, :update, :destroy]

  def index
    @search = @profile.results.search(params[:search])
    @search.meta_sort ||= "created_at.desc"
    @results = @search.paginate :per_page => 20, :page => params[:page]
  end

  def new
    @result = @profile.results.build
  end

  def create
    @result = @profile.results.build(params[:result])
    
    if @result.save
      flash[:notice] = "Result was successfully created"
      redirect_to profile_results_path(@profile)
    else
      render :action => "new"
    end
  end

  def edit
    @profile = @result.profile
  end
  
  def update
    @profile = @result.profile
    
    if @result.update_attributes(params[:result])
      flash[:notice] = "Result was successfully updated"
      redirect_to profile_results_path(@profile)
    else
      render :action => "edit"
    end
  end

  def destroy
    @result.destroy
    
    flash[:notice] = "Result was successfully deleted"
    redirect_to profile_results_path(@result.profile)
  end
  
  private
  def find_parent_resource
    @profile = current_user.profiles.find(params[:profile_id])
  end
  
  def find_resource
    @result = @profile.results.find(params[:id])
  end
  
end

app/helpers/api/results_helper.rb
module Api::ResultsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.haml
= simple_form_for [@profile, @result] do |f|
  = f.input :name
  = f.input :result
  = f.input :units
  = f.input :date
  = f.input :note
  = f.button :submit, "Save"

app/views/results/edit.html.haml
= render "profiles/header", :profile => @profile

%h2 Edit result

= render "form"

app/views/results/index.html.haml
= render "profiles/header", :profile => @profile

%h2 Results

.add_link= link_to "New result", new_profile_result_path(@profile)

- if @results.present?
  #results_container
    %table.zebra
      %tr
        %th{:style => "width: 30%"}= sort_link @search, :name, "Name"
        %th{:style => "width: 20%"} Result
        %th{:style => "width: 20%"}= sort_link @search, :date, "Date"
        %th{:style => "width: 20%"}= sort_link @search, :created_at, "Created at"
        %th{:style => "width: 10%"}
      - @results.each do |result|
        %tr{:class => cycle('even', 'odd')}
          %td= result.name
          %td= "#{result.result} #{result.units}"
          %td= l(result.date)
          %td= l(result.created_at)
          %td
            %ul.icon_menu
              %li= link_to image_tag("icons/edit.png", :alt => "edit"), edit_profile_result_path(@profile, result)
              %li= link_to image_tag("icons/delete.png", :alt => "delete"), profile_result_path(@profile, result), :method => :delete, :confirm => "Do you really want to delete this result?"
  = will_paginate @results
- else
  %p No results found.

app/views/results/new.html.haml
= render "profiles/header", :profile => @profile

%h2 New result

= render "form"