config/routes.rb
Webehr::Application.routes.draw do
  
  root :to => "profiles#index"
  
  resources :profiles, :except => [:show] do
    resources :medications, :except => [:show]
    resources :results, :except => [:show]
  end
  
  resources :users, :only => [:index]
  
  resource :account, :only => [:show, :edit, :update] do
    get :edit_password
    put :update_password
  end
  
  devise_for :users

  namespace :api do
    resources :profiles, :only => [:index] do
      resources :medications, :only => [:create, :destroy]
      resources :results, :only => [:create, :destroy]
    end
  end
  
end

app/helpers/layout_helper.rb
module LayoutHelper
  
  def flash_notice
    html = ''
    flash.each do |name, msg|
      html += content_tag :div, msg, :class => name
    end
    html.html_safe
  end
  
  def selected_if(condition)
    "selected" if condition
  end
  
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Electronic Health Record
    %meta{'http-equiv' => 'Content-Type', :content => 'text/html;charset=utf-8'}
    = stylesheet_link_tag 'reset', 'ui-lightness/jquery-ui', 'form', 'style', 'application'
    = javascript_include_tag "jquery.min", "jquery-ui.min", "jquery.ui.datepicker-pl", "rails", "application"
    = csrf_meta_tag
  %body{:class => "#{controller_name}_controller"}
    #container{:class => action_name}
      #sidebar
        #logo
          = link_to image_tag('logo.png', :alt => "EHR"), root_path
        %ul
          %li.profiles{:class => selected_if(controller_name != "users")}
            = link_to profiles_path do
              Profiles
              - if current_user.present?
                %span.count= "(#{current_user.profiles.count})"
          %li.users{:class => selected_if(controller_name == "users")}
            = link_to users_path do
              Users
              - if current_user.present?
                %span.count= "(#{User.count})"
          %li.account{:class => selected_if(controller_name == "accounts")}
            = link_to "Account", account_path
        
      #content
        #flash
          = flash_notice unless flash.blank?
        = yield
        
    #loader 
      = image_tag("/images/loader.gif")
      Trwa ładowanie...